// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAheqyhDRMupjhhfDnBt5KDw0HU31urAWk',
    appId: '1:573711518088:web:32cb0d3e26da3299c1123d',
    messagingSenderId: '573711518088',
    projectId: 'auth-modul-b8370',
    authDomain: 'auth-modul-b8370.firebaseapp.com',
    storageBucket: 'auth-modul-b8370.firebasestorage.app',
    measurementId: 'G-T0HJSK9XMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIT2dU_MdpWdiSyyCvcuBjOJCjGPMz5eY',
    appId: '1:573711518088:android:238138f3ee906fb8c1123d',
    messagingSenderId: '573711518088',
    projectId: 'auth-modul-b8370',
    storageBucket: 'auth-modul-b8370.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRZrp33BNucFhCJg2rGXxawZb5_eJhDlk',
    appId: '1:573711518088:ios:2f69f05b0fa4e6fcc1123d',
    messagingSenderId: '573711518088',
    projectId: 'auth-modul-b8370',
    storageBucket: 'auth-modul-b8370.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthTrial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRZrp33BNucFhCJg2rGXxawZb5_eJhDlk',
    appId: '1:573711518088:ios:2f69f05b0fa4e6fcc1123d',
    messagingSenderId: '573711518088',
    projectId: 'auth-modul-b8370',
    storageBucket: 'auth-modul-b8370.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthTrial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAheqyhDRMupjhhfDnBt5KDw0HU31urAWk',
    appId: '1:573711518088:web:8e6e548367be747dc1123d',
    messagingSenderId: '573711518088',
    projectId: 'auth-modul-b8370',
    authDomain: 'auth-modul-b8370.firebaseapp.com',
    storageBucket: 'auth-modul-b8370.firebasestorage.app',
    measurementId: 'G-ZDCP0JW9Z0',
  );
}
